export const MAX_OPEN_ORDER = 1000;

export const ORDER_STATUS = {
  NEW: "NEW",
  ACTIVE: "ACTIVE",
  OPEN: "ACTIVE",
  PARTIAL: "PARTIALLY_FILLED",
  PARTIALLY_FILLED: "PARTIALLY_FILLED",
  FILLED: "FILLED",
  CANCELED: "CANCELED",
  REJECTED: "REJECTED",
  CANCELLING: "CANCELLING",
  COMPLETED: "COMPLETED",
  EXPIRED: "EXPIRED",
};
